In [1]:
import pandas as pd

In [2]:
dfSwfVal = pd.read_csv('val1460128715760047_Rrs_mod.csv',header=0,index_col=0)

In [3]:
dfSwfVal.head()

,cruise_name,file_name,date_time,latitude,longitude,seawifs_npixel,seawifs_tdiff,seawifs_solz,seawifs_senz,seawifs_cv,...,insitu_Rrs490,insitu_Rrs510,insitu_Rrs555,insitu_Rrs670,seawifs_Rrs412,seawifs_Rrs443,seawifs_Rrs490,seawifs_Rrs510,seawifs_Rrs555,seawifs_Rrs670
id,,,,,,,,,,,,,,,,,,,,,
31,s990610w,S1999161164837.L2_MLAC.R0000021509_43N_43N_68W...,1999/06/10 14:30:00,43.695,-68.040,100,9180,21.700,22.172,0.0170,...,-999.000000,0.005483,-999.000000,-999.000000,0.002981,0.003594,0.004094,0.003724,0.002715,0.000317
32,s990610w,S1999161164837.L2_MLAC.R0000021509_43N_43N_68W...,1999/06/10 16:00:00,43.679,-68.646,100,3780,21.533,23.056,0.0510,...,0.004774,0.004477,0.004331,0.001113,0.001943,0.002601,0.003336,0.003321,0.003147,0.000510
99,s990824w,S1999236162323.L2_MLAC.R0000021516_43N_43N_68W...,1999/08/24 17:30:00,43.713,-67.756,100,-3300,32.622,46.042,0.0517,...,0.007052,0.005878,0.004736,-999.000000,0.004441,0.004172,0.003767,0.002986,0.002044,0.000129
125,s990802w,S1999214163307.L2_MLAC.R0000021513_43N_43N_68W...,1999/08/02 16:00:00,43.745,-66.986,100,2760,26.128,31.354,0.0388,...,-999.000000,0.004385,-999.000000,-999.000000,0.002260,0.002420,0.002716,0.002618,0.002335,0.000418
228,s000712w,S2000194161838.L2_MLAC.R0000021391_43N_43N_68W...,2000/07/12 14:30:00,43.755,-66.603,100,7380,21.903,42.950,0.0395,...,0.003525,0.003403,0.002944,0.000443,0.002083,0.002601,0.003412,0.003169,0.002577,0.000319

In [9]:
dfSwfVal.columns.tolist()

['cruise_name',
 'file_name',
 'date_time',
 'latitude',
 'longitude',
 'seawifs_npixel',
 'seawifs_tdiff',
 'seawifs_solz',
 'seawifs_senz',
 'seawifs_cv',
 'seawifs_es_thresh',
 'seawifs_windspeed',
 'insitu_Rrs412',
 'insitu_Rrs443',
 'insitu_Rrs490',
 'insitu_Rrs510',
 'insitu_Rrs555',
 'insitu_Rrs670',
 'seawifs_Rrs412',
 'seawifs_Rrs443',
 'seawifs_Rrs490',
 'seawifs_Rrs510',
 'seawifs_Rrs555',
 'seawifs_Rrs670',
 'L1_name']

In [4]:
def ConvertFileName(name):
    spl = name.split('L2')
    spl2 = spl[1].split('_OCVAL')
    return spl[0] + 'L1A' + spl2[0] + spl2[1]

In [6]:
dfSwfVal['L1_name'] = dfSwfVal['file_name'].map(ConvertFileName)

In [7]:
dfSwfVal.head()

,cruise_name,file_name,date_time,latitude,longitude,seawifs_npixel,seawifs_tdiff,seawifs_solz,seawifs_senz,seawifs_cv,...,insitu_Rrs510,insitu_Rrs555,insitu_Rrs670,seawifs_Rrs412,seawifs_Rrs443,seawifs_Rrs490,seawifs_Rrs510,seawifs_Rrs555,seawifs_Rrs670,L1_name
id,,,,,,,,,,,,,,,,,,,,,
31,s990610w,S1999161164837.L2_MLAC.R0000021509_43N_43N_68W...,1999/06/10 14:30:00,43.695,-68.040,100,9180,21.700,22.172,0.0170,...,0.005483,-999.000000,-999.000000,0.002981,0.003594,0.004094,0.003724,0.002715,0.000317,S1999161164837.L1A_MLAC.R0000021509_43N_43N_68...
32,s990610w,S1999161164837.L2_MLAC.R0000021509_43N_43N_68W...,1999/06/10 16:00:00,43.679,-68.646,100,3780,21.533,23.056,0.0510,...,0.004477,0.004331,0.001113,0.001943,0.002601,0.003336,0.003321,0.003147,0.000510,S1999161164837.L1A_MLAC.R0000021509_43N_43N_68...
99,s990824w,S1999236162323.L2_MLAC.R0000021516_43N_43N_68W...,1999/08/24 17:30:00,43.713,-67.756,100,-3300,32.622,46.042,0.0517,...,0.005878,0.004736,-999.000000,0.004441,0.004172,0.003767,0.002986,0.002044,0.000129,S1999236162323.L1A_MLAC.R0000021516_43N_43N_68...
125,s990802w,S1999214163307.L2_MLAC.R0000021513_43N_43N_68W...,1999/08/02 16:00:00,43.745,-66.986,100,2760,26.128,31.354,0.0388,...,0.004385,-999.000000,-999.000000,0.002260,0.002420,0.002716,0.002618,0.002335,0.000418,S1999214163307.L1A_MLAC.R0000021513_43N_43N_68...
228,s000712w,S2000194161838.L2_MLAC.R0000021391_43N_43N_68W...,2000/07/12 14:30:00,43.755,-66.603,100,7380,21.903,42.950,0.0395,...,0.003403,0.002944,0.000443,0.002083,0.002601,0.003412,0.003169,0.002577,0.000319,S2000194161838.L1A_MLAC.R0000021391_43N_43N_68...

In [8]:
dfSwfVal.to_pickle('dfMatchUpSWF.pkl')

In [53]:

import requests
for idx in dfSwfVal.index:
    fname = dfSwfVal.loc[idx,'L1_name']
    url = 'http://oceandata.sci.gsfc.nasa.gov/cgi/getfile/' + fname
    r = requests.get(url)
    with open(fname,'wb') as f:
        f.write(r.content)